export const entityOwnershipData = () => {
  // return {
  //   owner: {name: "Your Own PBM"},
  //   client: {name: "Medicare"},
  //   carrier: {name: "Medicare S1234"},
  //   account: {accountno: "1234"},
  //   groups: [
  //     {
  //       id: 123,
  //       list: [
  //         "Free First Fill",
  //         "Home Infusion",
  //         "Additional Demonstratal Drugs(MMP Only)",
  //         "Value-Based Insurance",
  //         "Full Gap Coverage",
  //         "OTC Benefits",
  //         "Indicated-Base Coverage",
  //         "Senior Savings Model",
  //         "Partial Gap Coverage",
  //         "Excluded Drugs",
  //         "LIS Cost Sharing Reduction",
  //         "Other 1",
  //         "Other 2",
  //         "Other 3",
  //         "Other 4",
  //         "Other 5",
  //       ],
  //     },
  //     {
  //       id: 123,
  //       list: [
  //         "Free First Fill",
  //         "Home Infusion",
  //         "Additional Demonstratal Drugs(MMP Only)",
  //         "Value-Based Insurance",
  //         "Full Gap Coverage",
  //         "OTC Benefits",
  //         "Indicated-Base Coverage",
  //         "Senior Savings Model",
  //         "Partial Gap Coverage",
  //         "Excluded Drugs",
  //         "LIS Cost Sharing Reduction",
  //         "Other 1",
  //         "Other 2",
  //         "Other 3",
  //         "Other 4",
  //         "Other 5",
  //       ],
  //     },
  //     {
  //       id: 112,
  //       list: [
  //         "Free First Fill",
  //         "Home Infusion",
  //         "Additional Demonstratal Drugs(MMP Only)",
  //         "Value-Based Insurance",
  //         "Full Gap Coverage",
  //         "OTC Benefits",
  //         "Indicated-Base Coverage",
  //         "Senior Savings Model",
  //         "Partial Gap Coverage",
  //         "Excluded Drugs",
  //         "LIS Cost Sharing Reduction",
  //         "Other 1",
  //         "Other 2",
  //         "Other 3",
  //         "Other 4",
  //         "Other 5",
  //       ],
  //     },
  //   ],
  // };

  return {
    customer: {
      owner: "Your Own PBM",
      client: "Medicare",
      carrier: "Medicare S1234",
      account: "1234",
      groups: [
        {
          id: 123,
          list: [
            "Free First Fill",
            "Home Infusion",
            "Additional Demonstratal Drugs(MMP Only)",
            "Value-Based Insurance",
            "Full Gap Coverage",
            "OTC Benefits",
            "Indicated-Base Coverage",
            "Senior Savings Model",
            "Partial Gap Coverage",
            "Excluded Drugs",
            "LIS Cost Sharing Reduction",
            "Other 1",
            "Other 2",
            "Other 3",
            "Other 4",
            "Other 5",
          ],
        },
        {
          id: 123,
          list: [
            "Free First Fill",
            "Home Infusion",
            "Additional Demonstratal Drugs(MMP Only)",
            "Value-Based Insurance",
            "Full Gap Coverage",
            "OTC Benefits",
            "Indicated-Base Coverage",
            "Senior Savings Model",
            "Partial Gap Coverage",
            "Excluded Drugs",
            "LIS Cost Sharing Reduction",
            "Other 1",
            "Other 2",
            "Other 3",
            "Other 4",
            "Other 5",
          ],
        },
        {
          id: 112,
          list: [
            "Free First Fill",
            "Home Infusion",
            "Additional Demonstratal Drugs(MMP Only)",
            "Value-Based Insurance",
            "Full Gap Coverage",
            "OTC Benefits",
            "Indicated-Base Coverage",
            "Senior Savings Model",
            "Partial Gap Coverage",
            "Excluded Drugs",
            "LIS Cost Sharing Reduction",
            "Other 1",
            "Other 2",
            "Other 3",
            "Other 4",
            "Other 5",
          ],
        },
      ],
    },
  };
};

export const entityOwnershipData1 = () => {
  return {
    customer: {
      owner: { value: "TESTFRX", default: false },
      client: { value: "NFL", default: false },
      carrier: { value: "NFC", default: false },
      account: { value: "VIKINGS", default: false },
      groups: [
        {
          id: "MNVIKPPO",
          list: [
            // "Free First Fill",
            // "Home Infusion",
            // "Additional Demonstratal Drugs(MMP Only)",
            // "Value-Based Insurance",
            // "Full Gap Coverage",
            // "OTC Benefits",
            // "Indicated-Base Coverage",
            // "Senior Savings Model",
            // "Partial Gap Coverage",
            // "Excluded Drugs",
            // "LIS Cost Sharing Reduction",
            // "Other 1",
            // "Other 2",
            // "Other 3",
            // "Other 4",
            // "Other 5",
          ],
          default: true,
        },
        {
          id: "MNVIKHSA",
          list: [
            // "Free First Fill",
            // "Home Infusion",
            // "Additional Demonstratal Drugs(MMP Only)",
            // "Value-Based Insurance",
            // "Full Gap Coverage",
            // "OTC Benefits",
            // "Indicated-Base Coverage",
            // "Senior Savings Model",
            // "Partial Gap Coverage",
            // "Excluded Drugs",
            // "LIS Cost Sharing Reduction",
            // "Other 1",
            // "Other 2",
            // "Other 3",
            // "Other 4",
            // "Other 5",
          ],
          default: false,
        },
        {
          id: "MNVIKHDHP",
          list: [
            // "Free First Fill",
            // "Home Infusion",
            // "Additional Demonstratal Drugs(MMP Only)",
            // "Value-Based Insurance",
            // "Full Gap Coverage",
            // "OTC Benefits",
            // "Indicated-Base Coverage",
            // "Senior Savings Model",
            // "Partial Gap Coverage",
            // "Excluded Drugs",
            // "LIS Cost Sharing Reduction",
            // "Other 1",
            // "Other 2",
            // "Other 3",
            // "Other 4",
            // "Other 5",
          ],
          default: false,
        },
      ],
    },
  };
};
